### ISSUE TITLE
Graph Classification Task

### ISSUE THREAD

**Issue by Wienhannover** [GraphFramEx/graphframex#1]
Is GraphFramEx extendable on graph classification task? If yes, what part of the code base should be changed? Thanks very much in advance.

**Comment by k-amara** [comment]
Hi! GraphFramEx is now available for graph classification as well!
Set args.graph_classification as 'True'
We are still working on adding more explainability methods for GC
Best

**Comment by Wienhannover** [comment]
thanks very much for your work.
